<form action="" method="post">
    <fieldset>
        <label for="email"></label>
        <input type="email" name="email" id="">
    </fieldset>
    <fieldset>
        <label for="first_name">Prénom</label>
        <input type="text" name="first_name" />
    </fieldset>
    <fieldset>
        <label for="last_name">Nom</label>
        <input type="text" name="last_name" />
    </fieldset>
    <input type="submit" value="Créer">
</form>