<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?= $title ?></title>
</head>

<body>
    <header>
        <nav>
            <a href="index.php?route=show_user">Read</a>
            <a href="index.php?route=create_user">Create</a>
            <a href="index.php?route=update_user">Update</a>
            <a href="index.php?route=delete_user">Delete</a>
        </nav>
    </header>
    <main>
        <?= require $template ?>
    </main>

</body>

</html>