<main>
    <h2>
        <?= $pageTitle; ?>
    </h2>
    <form action="controllers/user-form.php" method="post">
        <!-- Champs du formulaire -->
        <label for="email">Email :</label>
        <input type="email" id="email" name="email" required>
        <label for="password">Mot de passe :</label>
        <input type="password" id="password" name="password" required>
        <label for="confirm_password">Confirmer le mot de passe :</label>
        <input type="password" id="confirm_password" name="confirm_password" required>
        <label for="newsletter"> S'inscrire à la newsletter </label>
        <input type="checkbox" name="newsletter" value="1">
        <button type="submit">Envoyer</button>
    </form>
</main>