<main>
    <h2>
        <?= $pageTitle; ?>
    </h2>
    <form action="<?= dirname(__DIR__ . '../../controllers/user-form.php'); ?>" method="post">
        <!-- Champs du formulaire -->
        <label for="email">Email :</label>
        <input type="email" id="email" name="email" required>
        <label for="password">Mot de passe :</label>
        <input type="password" id="password" name="password" required>
        <button type="submit">Envoyer</button>
    </form>
</main>