<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <title>Exercices Formulaires</title>
    <link rel="stylesheet" href="assets/styles/style.css">
</head>

<body>
    <?php 
    if($route === null || $route === "home") {
        require "home.phtml";
    } else if ($route === "inscription") {
        require "register.phtml";
    } else if ($route === "connexion"){
        require "login.phtml";
    };
    ?>
</body>

</html>